version: '2'
services:
  freepbx:
#    build: .
    image: netlife/PBX
    container_name: freepbx

#    network_mode: "host"
    ports:
    - "5160-5161:5160-5161/udp"
    - "5060-5060:5060-5060/udp"
    - "8082:8082/tcp"
    - "10000-10050:10000-10050/udp"
    
    volumes:
      - freepbx-apache:/etc/apache2
      - freepbx-asterisk-config:/etc/asterisk
      - freepbx-mysql:/var/lib/mysql
      - freepbx-asterisk-spool:/var/spool/asterisk
      - freepbx-asterisk-data:/var/lib/asterisk

volumes:
  freepbx-apache:
  freepbx-asterisk-config:
  freepbx-mysql:
  freepbx-asterisk-spool:
  freepbx-asterisk-data:
